2-module/2-task, 2-module/3-task решил, автотесты проходят
js-tasks-ru/jsbasic-20201214_p-kondrashin pull request #3
Opened 2020-12-21 18:39 UTC by Petr-Ko

2020-12-21 20:11 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Определите, пуст ли объект
+ объект со свойством undefined должен считаться не пустым
+ {} должен вернуть true
+ объект с удалённым свойством - пустой
+ если у объекта есть хоть одно свойство, то он не пустой
```
```diff
Создайте калькулятор
+ должно умножать числа
+ должно складывать числа
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-22 16:22 UTC, SinimaWath requested changes

2020-12-22 16:22 UTC, SinimaWath commented on 2-module/2-task/index.js
> +      i++;
Давай попробуем сделать без счетчика ;)

2020-12-22 16:22 UTC, SinimaWath commented on 2-module/2-task/index.js
> +
Тут все таки лишний отступ. Он не нужен сразу после функции

2020-12-22 20:22 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Создайте калькулятор
+ должно умножать числа
+ должно складывать числа
```
```diff
Определите, пуст ли объект
+ если у объекта есть хоть одно свойство, то он не пустой
+ {} должен вернуть true
+ объект с удалённым свойством - пустой
+ объект со свойством undefined должен считаться не пустым
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-22 21:52 UTC, SinimaWath approved these changes

2020-12-22 21:53 UTC, merged